package com.habibInc.issueTracker.column;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;

import static org.assertj.core.api.Assertions.*;
import static org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase.*;

@DataJpaTest
@AutoConfigureTestDatabase(replace = Replace.NONE)
public class ColumnRepositoryTest {
    @Autowired
    ColumnRepository columnRepository;

    Column column;

    @BeforeEach
    public void setup() {
        column = new Column();
        column.setName("Done");
    }

    @Test
    public void itShouldSaveColumn() {
        // when invoking the column repository to save a new column
        Column response = columnRepository.save(column);

        // then the column should be saved successfully with an autogenerated id
        assertThat(response).isEqualToComparingOnlyGivenFields(column);
        assertThat(response.getId()).isNotNull().isPositive();
    }
}
