package com.habibInc.issueTracker.sprint;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;

import java.time.LocalDateTime;

import static org.assertj.core.api.Assertions.*;
import static org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase.*;

@DataJpaTest
@AutoConfigureTestDatabase(replace = Replace.NONE)
public class SprintRepositoryTest {

    @Autowired
    SprintRepository sprintRepository;

    Sprint sprint;

    @BeforeEach
    public void setup() {
        sprint = Sprint.builder()
                .name("Primary sprint")
                .goal("Primary sprint goal")
                .startDate(LocalDateTime.now())
                .endDate(LocalDateTime.now().plusDays(15))
                .build();
    }

    @Test
    public void itShouldSaveSprint() {
        // when the sprint is saved
        Sprint savedSprint = sprintRepository.save(sprint);

        // then expect its id to have been autogenerated
        assertThat(savedSprint).isEqualToComparingOnlyGivenFields(sprint);
        assertThat(savedSprint.getId()).isNotNull().isPositive();
    }

}
