package com.habibInc.issueTracker.project;

import com.habibInc.issueTracker.issue.Issue;
import com.habibInc.issueTracker.issue.IssueRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;

import java.util.List;

import static org.assertj.core.api.Assertions.*;
import static org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase.*;

@DataJpaTest
@AutoConfigureTestDatabase(replace = Replace.NONE)
public class ProjectRepositoryTest {

    @Autowired
    ProjectRepository projectRepository;

    @Autowired
    IssueRepository issueRepository;

    Project project, project2;

    @BeforeEach
    public void setup() {
        project = new Project();
        project.setName("Primary project");

        project2 = new Project();
        project2.setName("Secondary project");
    }

    @Test
    public void itShouldSaveProject() {
        // when a project is saved
        Project savedProject = projectRepository.save(project);

        // then expect the id to be autogenerated and the response is the saved project
        assertThat(savedProject.getId()).isNotNull().isPositive();
        assertThat(savedProject).isEqualToComparingOnlyGivenFields(project);
    }

    @Test
    public void itShouldFindAllProjects() {
        List<Project> projects = List.of(project, project2);
        projectRepository.saveAll(projects);

        List<Project> retrievedProjects = (List<Project>) projectRepository.findAll();

        assertThat(retrievedProjects).isEqualTo(projects);
    }

    @Test
    public void itShouldFindAllIssuesByProjectId() {
        // given a project
        project = projectRepository.save(project);

        // given the project backlog
        List<Issue> backlog = List.of(
                Issue.builder().project(project).summary("issue 1").build(),
                Issue.builder().project(project).summary("issue 2").build(),
                Issue.builder().project(project).summary("issue 2").build()
        );

        // given the backlog is saved
        backlog = (List<Issue>) issueRepository.saveAll(backlog);

        // when issueRepository#findAllByProjectId is invoked
        List<Issue> retrievedBacklog =
                issueRepository.findAllByProjectId(project.getId());

        // then expect the project backlog to have been retrieved successfully
        assertThat(retrievedBacklog).hasSameElementsAs(backlog);
    }
}
