package com.habibInc.issueTracker.board;

import com.habibInc.issueTracker.column.Column;
import com.habibInc.issueTracker.column.ColumnRepository;
import com.habibInc.issueTracker.exceptionhandler.ApiError;
import com.habibInc.issueTracker.exceptionhandler.ResourceNotFoundException;
import com.habibInc.issueTracker.security.JwtUtil;
import com.habibInc.issueTracker.user.User;
import com.habibInc.issueTracker.user.UserRepository;
import com.habibInc.issueTracker.user.UserService;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.*;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class BoardIT {

    @Autowired
    TestRestTemplate restTemplate;

    @Autowired
    JwtUtil jwtUtil;

    @Autowired
    BoardService boardService;

    @Autowired
    BoardRepository boardRepository;

    @Autowired
    UserService userService;

    @Autowired
    UserRepository userRepository;

    @Autowired
    ColumnRepository columnRepository;

    User authenticatedUser;
    HttpHeaders httpHeaders;

    Board board;

    @BeforeAll
    public void authSetup() {
        // set up the authenticated user
        authenticatedUser = User.builder()
                .userName("authenticated_user")
                .email("authenticated@user.in")
                .password("auth_pass")
                .build();

        // save the user to pass the authorization filter
        userService.createUser(authenticatedUser);

        // generate an auth token for the authenticated user
        String token = jwtUtil.generateToken(authenticatedUser.getEmail());

        // set up the authorization header
        httpHeaders = new HttpHeaders();
        httpHeaders.add(JwtUtil.HEADER, JwtUtil.TOKEN_PREFIX + token);
    }

    @BeforeEach
    public void setup() {
        board = new Board();
        board.setName("ScrumOrKanban");
    }

    @Nested
    @DisplayName("POST")
    class Post {
        @Test
        public void itShouldCreateBoard() {
            // given the url endpoint and the request
            String url = "/boards";
            HttpEntity<Board> httpEntity = new HttpEntity<>(board, httpHeaders);

            // when a post request is made to create a new board
            ResponseEntity<Board> response =
                    restTemplate.exchange(url, HttpMethod.POST, httpEntity, Board.class);

            // then the board should be created successfully with an autogenerated id
            assertThat(response.getStatusCode()).isEqualTo(HttpStatus.CREATED);
            assertThat(response).isEqualToComparingOnlyGivenFields(board);
            assertThat(response.getBody().getId()).isNotNull().isPositive();

            // the authenticated user should be set as board owner
            assertThat(response.getBody().getOwner()).isEqualTo(authenticatedUser);
        }
    }

    @Nested
    @DisplayName("GET")
    class Get {
        @Test
        public void itShouldGetBoardById() {
            // given a board is created
            Board createdBoard = boardService.createBoard(board, authenticatedUser);

            // given the request
            String url = "/boards/" + createdBoard.getId();
            HttpEntity<Board> httpEntity = new HttpEntity<>(httpHeaders);

            // when a get request is made to fetch the board by id
            ResponseEntity<Board> response =
                    restTemplate.exchange(url, HttpMethod.GET, httpEntity, Board.class);

            // then the board should be retrieved successfully
            assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
            assertThat(response.getBody().getId()).isNotNull().isPositive();
            assertThat(response.getBody()).isEqualTo(createdBoard);
        }

        @Test
        public void givenGetBoardById_itShouldGetListOfColumns() {
            // given a board
            board = boardService.createBoard(board, authenticatedUser);

            // given a list of columns
            List<Column> columns = List.of(
                    Column.builder().title("column 1").board(board).build(),
                    Column.builder().title("column 2").board(board).build(),
                    Column.builder().title("column 3").board(board).build(),
                    Column.builder().title("column 4").board(board).build()
            );

            columns = (List<Column>) columnRepository.saveAll(columns);

            // given the request
            String url = "/boards/" + board.getId();
            HttpEntity<Board> httpEntity = new HttpEntity<>(httpHeaders);

            // when a GET request is made to fetch the board by id
            ResponseEntity<Board> response =
                    restTemplate.exchange(url, HttpMethod.GET, httpEntity, Board.class);

            // then the board should be retrieved along with a list of columns
            assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
            assertThat(response.getBody().getColumns()).isEqualTo(columns);
        }
    }

    @Nested
    @DisplayName("DELETE")
    class Delete{
        @Test
        public void itShouldDeleteBoardById() {
            // given a board
            board = boardService.createBoard(board, authenticatedUser);

            // given the request
            String url = "/boards/" + board.getId();
            HttpEntity<Board> httpEntity = new HttpEntity<>(httpHeaders);

            // when a DELETE request is made to delete the board by id
            ResponseEntity<String> response =
                    restTemplate.exchange(url, HttpMethod.DELETE, httpEntity, String.class);

            // then the board should be deleted successfully
            assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);

            assertThatExceptionOfType(ResourceNotFoundException.class)
                    .isThrownBy(() -> boardService.getBoardById(board.getId()))
                    .withMessageContaining("Board not found");
        }

        @Test
        public void whenBoardIsDeletedById_itShouldDeleteAllItsColumns() {
            // given the board is created
            board = boardService.createBoard(board, authenticatedUser);

            // given a list of columns belonging to the board
            columnRepository.saveAll(
                    List.of(
                            Column.builder().title("column 1").board(board).build(),
                            Column.builder().title("column 2").board(board).build(),
                            Column.builder().title("column 3").board(board).build(),
                            Column.builder().title("column 4").board(board).build()
                    )
            );

            // expect the columns to have been saved
            Iterable<Column> columns = columnRepository.findAll();
            assertThat(columns).isNotEmpty();

            // given the DELETE request
            String url = "/boards/" + board.getId();
            HttpEntity<Board> httpEntity = new HttpEntity<>(httpHeaders);

            // when the request is made to delete the board by id
            restTemplate.exchange(url, HttpMethod.DELETE, httpEntity, String.class);

            // then expect the board's list of columns to have been deleted
            columns = columnRepository.findAll();
            assertThat(columns).isEmpty();
        }

        @Test
        public void givenDeleteBoardById_whenAuthenticatedUserIsNotTheBoardOwner_itShouldReturnForbiddenOperationError() {
            // given a random user
            User notAuthenticatedUser = User.builder().email("not@authenticated.user").password("forbid").build();

            // save the random user
            notAuthenticatedUser = userService.createUser(notAuthenticatedUser);

            // given a board that belongs to a user other than the authenticated user
            board = boardService.createBoard(board, notAuthenticatedUser);

            // given the DELETE request
            String url = "/boards/" + board.getId();
            HttpEntity<Board> httpEntity = new HttpEntity<>(httpHeaders);

            // when the request is made to delete the board by id
            ResponseEntity<ApiError> response =
                    restTemplate.exchange(url, HttpMethod.DELETE, httpEntity, ApiError.class);

            // then expect a 403 forbidden operation error
            assertThat(response.getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
            assertThat(response.getBody().getErrorMessage()).contains("Forbidden operation");
        }
    }

    @AfterEach
    public void teardown() {
        boardRepository.deleteAll();
    }

    @AfterAll
    public void authTeardown() {
        userRepository.deleteAll();
    }
}
