package com.habibInc.issueTracker.board;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;

import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
public class BoardRepositoryTest {

    @Autowired
    BoardRepository boardRepository;

    Board board;

    @BeforeEach
    public void setup() {
        board = new Board();
        board.setName("Scrum");
    }

    @Test
    public void itShouldSaveBoard() {
        // when the save method is invoked
        Board savedBoard = boardRepository.save(board);

        // then the board should be successfully saved with an autogenerated positive id
        assertThat(savedBoard).isEqualToComparingOnlyGivenFields(board);
        assertThat(savedBoard.getId()).isNotNull().isPositive();
    }

    @Test
    public void itShouldFindBoardById() {
        // given a saved board
        Board savedBoard = boardRepository.save(board);

        // when find board by id is invoked
        Optional<Board> response = boardRepository.findById(savedBoard.getId());

        // then the board should be retrieved successfully
        assertThat(response.get()).isEqualTo(savedBoard);
    }

    @AfterEach
    public void teardown() {
        boardRepository.deleteAll();
    }
}
